"use client";

import { useEffect, useMemo, useState } from "react";
import { Workspace } from "@/ui";
import { AO_TODO_COMMAND_EVENT, AO_TODO_COMMAND_KEY, TODO_LIST_STORAGE_KEY, TODO_STORAGE_EVENT, TODO_STORAGE_KEY, applyTodoCommand, createSubtask, createTodo, moveSubtask, moveTodo, type AOTodoCommand, type TodoItem, type TodoList, type TodoSubtask } from "@/lib/todo-model";
import { userStorageKey } from "@/lib/user-storage";

type Filter = "all" | "open" | "done";

export default function TodoPage() {
  const [items, setItems] = useState<TodoItem[]>([]); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [filter, setFilter] = useState<Filter>("all"); const [ready, setReady] = useState(false);
  const [taskLists, setTaskLists] = useState<TodoList[]>([]); const [activeListId, setActiveListId] = useState(""); const [creatingList, setCreatingList] = useState(false); const [newListTitle, setNewListTitle] = useState("");
  const [drafts, setDrafts] = useState<Record<string, { title: string; description: string }>>({}); const [taskMenu, setTaskMenu] = useState<string | null>(null); const [taskEdit, setTaskEdit] = useState({ title: "", dueDate: "" });
  const [subMenu, setSubMenu] = useState<{ taskId: string; subtaskId: string } | null>(null); const [subEdit, setSubEdit] = useState(""); const [subDescription, setSubDescription] = useState(""); const [nestedDraft, setNestedDraft] = useState(""); const [dragTarget, setDragTarget] = useState<{ id: string; position: "before" | "after" } | null>(null); const [macroTarget, setMacroTarget] = useState<string | null>(null);
  const [expandedTasks, setExpandedTasks] = useState<Record<string, boolean>>({});

  useEffect(() => { try { const value = JSON.parse(localStorage.getItem(userStorageKey(TODO_STORAGE_KEY)) ?? "[]") as TodoItem[]; setItems(Array.isArray(value) ? value : []); } catch { setItems([]); } try { const value = JSON.parse(localStorage.getItem(userStorageKey(TODO_LIST_STORAGE_KEY)) ?? "[]") as TodoList[]; setTaskLists(Array.isArray(value) ? value.filter((list) => typeof list?.id === "string" && typeof list?.title === "string") : []); } catch { setTaskLists([]); } setReady(true); }, []);
  useEffect(() => { if (ready) localStorage.setItem(userStorageKey(TODO_STORAGE_KEY), JSON.stringify(items)); }, [items, ready]);
  useEffect(() => { if (ready) localStorage.setItem(userStorageKey(TODO_LIST_STORAGE_KEY), JSON.stringify(taskLists)); }, [taskLists, ready]);
  useEffect(() => { function syncFromTimeline() { try { const saved = JSON.parse(localStorage.getItem(userStorageKey(TODO_STORAGE_KEY)) ?? "[]") as TodoItem[]; if (Array.isArray(saved)) setItems(saved); } catch { /* ignore malformed local state */ } } window.addEventListener(TODO_STORAGE_EVENT, syncFromTimeline); return () => window.removeEventListener(TODO_STORAGE_EVENT, syncFromTimeline); }, []);
  useEffect(() => { if (!ready) return; function consume() { const raw = localStorage.getItem(userStorageKey(AO_TODO_COMMAND_KEY)); if (!raw) return; localStorage.removeItem(userStorageKey(AO_TODO_COMMAND_KEY)); try { const command = JSON.parse(raw) as AOTodoCommand; if (command.action === "todo-open" && command.taskId) { setFilter("all"); setActiveListId(""); setMacroTarget(command.taskId); requestAnimationFrame(() => document.querySelector(`[data-todo-id="${CSS.escape(command.taskId!)}"]`)?.scrollIntoView({ block: "center", behavior: "smooth" })); window.setTimeout(() => setMacroTarget(null), 2400); } else setItems((current) => assignNewTasksToActiveList(current, applyTodoCommand(current, command))); } catch { /* invalid command */ } } consume(); window.addEventListener(AO_TODO_COMMAND_EVENT, consume); return () => window.removeEventListener(AO_TODO_COMMAND_EVENT, consume); }, [ready, activeListId]);
  useEffect(() => { function dismiss(event: PointerEvent) { if (!(event.target instanceof Element && (event.target.closest("[data-todo-menu]") || event.target.closest("[data-todo-menu-toggle]")))) { setTaskMenu(null); setSubMenu(null); } } function escape(event: KeyboardEvent) { if (event.key === "Escape") { setTaskMenu(null); setSubMenu(null); } } document.addEventListener("pointerdown", dismiss); document.addEventListener("keydown", escape); return () => { document.removeEventListener("pointerdown", dismiss); document.removeEventListener("keydown", escape); }; }, []);

  const selectedList = taskLists.find((list) => list.id === activeListId) ?? null;
  const listItems = useMemo(() => items.filter((item) => !activeListId || item.listId === activeListId), [activeListId, items]);
  const visible = useMemo(() => listItems.filter((item) => filter === "all" || (filter === "done" ? item.completed : !item.completed)), [filter, listItems]);
  function assignNewTasksToActiveList(current: TodoItem[], next: TodoItem[]) { if (!activeListId) return next; const currentIds = new Set(current.map((item) => item.id)); return next.map((item) => currentIds.has(item.id) ? item : { ...item, listId: activeListId }); }
  function add() { const item = createTodo(title, "normal", undefined, description); if (!item) return; setItems((current) => [...current, activeListId ? { ...item, listId: activeListId } : item]); setTitle(""); setDescription(""); }
  function createTaskList() { const cleanTitle = newListTitle.trim(); if (!cleanTitle) return; const list: TodoList = { id: crypto.randomUUID(), title: cleanTitle, createdAt: new Date().toISOString() }; setTaskLists((current) => [...current, list]); setActiveListId(list.id); setFilter("all"); setNewListTitle(""); setCreatingList(false); }
  function chooseTaskList(value: string) { if (value === "__create__") { setCreatingList(true); return; } setActiveListId(value); setFilter("all"); }
  function updateDraft(id: string, patch: Partial<{ title: string; description: string }>) { setDrafts((current) => ({ ...current, [id]: { title: current[id]?.title ?? "", description: current[id]?.description ?? "", ...patch } })); }
  function addSubtask(id: string) { const draft = drafts[id] ?? { title: "", description: "" }; const subtask = createSubtask(draft.title, draft.description); if (!subtask) return; setItems((current) => current.map((item) => item.id === id ? { ...item, subtasks: [...(item.subtasks ?? []), subtask] } : item)); setDrafts((current) => ({ ...current, [id]: { title: "", description: "" } })); setExpandedTasks((current) => ({ ...current, [id]: true })); }
  function updateSubtask(taskId: string, subtaskId: string, transform: (value: TodoSubtask) => TodoSubtask) { setItems((current) => current.map((item) => item.id === taskId ? { ...item, subtasks: (item.subtasks ?? []).map((entry) => entry.id === subtaskId ? transform(entry) : entry) } : item)); }
  function openTaskMenu(item: TodoItem) { setSubMenu(null); setTaskEdit({ title: item.title, dueDate: item.dueDate ?? "" }); setTaskMenu((current) => current === item.id ? null : item.id); }
  function openSubMenu(taskId: string, item: TodoSubtask) { setTaskMenu(null); setSubEdit(item.title); setSubDescription(item.description ?? ""); setNestedDraft(""); setSubMenu((current) => current?.subtaskId === item.id ? null : { taskId, subtaskId: item.id }); }
  function saveSubMenu() { if (!subMenu || !subEdit.trim()) return; const child = createSubtask(nestedDraft); updateSubtask(subMenu.taskId, subMenu.subtaskId, (item) => ({ ...item, title: subEdit.trim(), description: subDescription.trim() || undefined, subtasks: child ? [...(item.subtasks ?? []), child] : item.subtasks })); setSubMenu(null); }

  return <Workspace title="To Do" subtitle={`${selectedList?.title ?? "Overview"} · ${listItems.filter((item) => !item.completed).length} open · ${listItems.filter((item) => item.completed).length} complete`} actions={<button type="button" className="ms-btn" onClick={() => setItems((current) => current.filter((item) => activeListId ? item.listId !== activeListId || !item.completed : !item.completed))}>Clear completed</button>}>
    <section className="ms-panel ms-todo-panel">
      <div className="ms-todo-list-bar">
        <label className="ms-todo-list-picker"><span>Folders</span><select aria-label="Select To Do list" value={activeListId} onChange={(event) => chooseTaskList(event.target.value)}><option value="">Overview</option>{taskLists.map((list) => <option key={list.id} value={list.id}>{list.title}</option>)}<option value="__create__">+ Create task list…</option></select></label>
        <p className="ms-muted">{selectedList ? `Tasks in ${selectedList.title}` : "Overview contains every To Do, including tasks in saved lists."}</p>
      </div>
      {creatingList && <form className="ms-todo-new-list" onSubmit={(event) => { event.preventDefault(); createTaskList(); }}><input autoFocus aria-label="New task list name" value={newListTitle} onChange={(event) => setNewListTitle(event.target.value)} placeholder="Name this task list…" /><button className="ms-btn ms-btn-primary" type="submit" disabled={!newListTitle.trim()}>Create list</button><button className="ms-btn" type="button" onClick={() => { setCreatingList(false); setNewListTitle(""); }}>Cancel</button></form>}
      <div className="ms-todo-add"><input aria-label="New task" value={title} onChange={(event) => setTitle(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") add(); }} placeholder="Add a task…" /><input aria-label="New task description" value={description} onChange={(event) => setDescription(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") add(); }} placeholder="Description (optional)" /><button type="button" className="ms-btn ms-btn-primary" onClick={add}>Add</button></div>
      <div className="ms-todo-filters" aria-label="Task filters">{(["all", "open", "done"] as Filter[]).map((value) => <button type="button" className={filter === value ? "is-active" : ""} onClick={() => setFilter(value)} key={value}>{value}</button>)}</div>
      <div className="ms-todo-list">{visible.map((item) => <article data-todo-id={item.id} className={`ms-todo-item${item.completed ? " is-done" : ""}${dragTarget?.id === item.id ? ` is-drop-${dragTarget.position}` : ""}${macroTarget === item.id ? " is-macro-target" : ""}`} key={item.id} onDragOver={(event) => { event.preventDefault(); const rect = event.currentTarget.getBoundingClientRect(); setDragTarget({ id: item.id, position: event.clientY < rect.top + rect.height / 2 ? "before" : "after" }); }} onDrop={(event) => { event.preventDefault(); const source = event.dataTransfer.getData("text/todo-item"); if (source) setItems((current) => moveTodo(current, source, item.id, dragTarget?.position ?? "before")); setDragTarget(null); }}>
        <button type="button" className="ms-todo-drag" draggable aria-label={`Move ${item.title}`} onDragStart={(event) => event.dataTransfer.setData("text/todo-item", item.id)} onDragEnd={() => setDragTarget(null)}>⠿</button><input type="checkbox" checked={item.completed} aria-label={`Complete ${item.title}`} onChange={() => setItems((current) => current.map((entry) => entry.id === item.id ? { ...entry, completed: !entry.completed } : entry))} /><button type="button" className="ms-todo-disclosure" aria-label={`${expandedTasks[item.id] ? "Hide" : "Show"} details for ${item.title}`} aria-expanded={Boolean(expandedTasks[item.id])} onClick={() => setExpandedTasks((current) => ({ ...current, [item.id]: !current[item.id] }))}>⌄</button>
        <span><strong>{item.title}</strong><small>{item.priority === "high" ? "High priority" : "Task"}{item.dueDate ? ` · Due ${item.dueDate}` : ""}{item.subtasks?.length ? ` · ${item.subtasks.filter((subtask) => subtask.completed).length}/${item.subtasks.length} subtasks` : ""}</small></span>
        <div className="ms-todo-actions"><button type="button" data-todo-menu-toggle aria-label={`Edit ${item.title}`} aria-expanded={taskMenu === item.id} onClick={() => openTaskMenu(item)}>•••</button><button type="button" className="ms-todo-delete" aria-label={`Delete ${item.title}`} onClick={() => setItems((current) => current.filter((entry) => entry.id !== item.id))}>×</button></div>
        {taskMenu === item.id && <form className="ms-todo-menu" data-todo-menu onSubmit={(event) => { event.preventDefault(); const clean = taskEdit.title.trim(); if (clean) setItems((current) => current.map((entry) => entry.id === item.id ? { ...entry, title: clean, dueDate: taskEdit.dueDate || undefined } : entry)); setTaskMenu(null); }}><label>Task title<input autoFocus value={taskEdit.title} onChange={(event) => setTaskEdit((current) => ({ ...current, title: event.target.value }))} /></label><label>Due date<input type="date" value={taskEdit.dueDate} onChange={(event) => setTaskEdit((current) => ({ ...current, dueDate: event.target.value }))} /></label><div><button type="button" onClick={() => setTaskEdit((current) => ({ ...current, dueDate: "" }))}>Clear date</button><button type="submit">Save</button></div></form>}
        {expandedTasks[item.id] && <div className="ms-todo-detail"><textarea aria-label={`Description for ${item.title}`} value={item.description ?? ""} onChange={(event) => setItems((current) => current.map((entry) => entry.id === item.id ? { ...entry, description: event.target.value } : entry))} placeholder="Add a task description…" />
          {(item.subtasks ?? []).map((subtask) => <div className="ms-subtask-wrap" key={subtask.id} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.stopPropagation(); const source = event.dataTransfer.getData("text/todo-subtask"); if (source) setItems((current) => moveSubtask(current, item.id, source, subtask.id)); }}><div className={`ms-subtask${subtask.completed ? " is-done" : ""}`}><button type="button" className="ms-subtask-drag" draggable aria-label={`Move subtask ${subtask.title}`} onDragStart={(event) => { event.stopPropagation(); event.dataTransfer.setData("text/todo-subtask", subtask.id); }}>⠿</button><input type="checkbox" checked={subtask.completed} aria-label={`Complete subtask ${subtask.title}`} onChange={() => updateSubtask(item.id, subtask.id, (entry) => ({ ...entry, completed: !entry.completed }))} /><span><strong>{subtask.title}</strong>{subtask.description && <small>{subtask.description}</small>}</span><button type="button" data-todo-menu-toggle aria-label={`Options for subtask ${subtask.title}`} onClick={() => openSubMenu(item.id, subtask)}>•••</button><button type="button" aria-label={`Delete subtask ${subtask.title}`} onClick={() => setItems((current) => current.map((entry) => entry.id === item.id ? { ...entry, subtasks: (entry.subtasks ?? []).filter((candidate) => candidate.id !== subtask.id) } : entry))}>×</button></div>
            {subMenu?.subtaskId === subtask.id && <form className="ms-todo-menu ms-subtask-menu" data-todo-menu onSubmit={(event) => { event.preventDefault(); saveSubMenu(); }}><label>Subtask title<input autoFocus value={subEdit} onChange={(event) => setSubEdit(event.target.value)} /></label><label>Subtask description<textarea value={subDescription} onChange={(event) => setSubDescription(event.target.value)} placeholder="Optional description" /></label><label>Add one nested subtask<input value={nestedDraft} onChange={(event) => setNestedDraft(event.target.value)} placeholder="Optional" /></label><button type="submit">Save</button></form>}
            {(subtask.subtasks ?? []).map((child) => <div className={`ms-nested-subtask${child.completed ? " is-done" : ""}`} key={child.id}><input type="checkbox" checked={child.completed} aria-label={`Complete nested subtask ${child.title}`} onChange={() => updateSubtask(item.id, subtask.id, (entry) => ({ ...entry, subtasks: (entry.subtasks ?? []).map((candidate) => candidate.id === child.id ? { ...candidate, completed: !candidate.completed } : candidate) }))} /><span>{child.title}</span><button type="button" aria-label={`Delete nested subtask ${child.title}`} onClick={() => updateSubtask(item.id, subtask.id, (entry) => ({ ...entry, subtasks: (entry.subtasks ?? []).filter((candidate) => candidate.id !== child.id) }))}>×</button></div>)}
          </div>)}
          <div className="ms-subtask-add"><input aria-label={`New subtask for ${item.title}`} value={drafts[item.id]?.title ?? ""} onChange={(event) => updateDraft(item.id, { title: event.target.value })} placeholder="Add a subtask…" /><input aria-label={`Subtask description for ${item.title}`} value={drafts[item.id]?.description ?? ""} onChange={(event) => updateDraft(item.id, { description: event.target.value })} onKeyDown={(event) => { if (event.key === "Enter") addSubtask(item.id); }} placeholder="Description (optional)" /><button type="button" onClick={() => addSubtask(item.id)}>Add subtask</button></div>
        </div>}
      </article>)}{!visible.length && <p className="ms-muted ms-todo-empty">No tasks in this view.</p>}</div>
    </section>
  </Workspace>;
}
