"use client";

import { type FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { Workspace } from "@/ui";
import { api, ApiError } from "@/lib/client-api";
import { userStorageKey } from "@/lib/user-storage";
import { MarkdownPreview } from "@/components/MarkdownPreview";

type Note = { id: string; title: string; body: string; updatedAt: string };
type ChatMessage = { role: "user" | "assistant"; content: string };
type Verification = { note: { id: string; title: string; updatedAt: string }; summary: string; method: string[]; confirmed: { assertion: string; status: "confirmed" | "partially-confirmed" | "unconfirmed" | "contradicted"; explanation: string; evidenceIds: string[] }[]; evidence: { id: string; title: string; url: string; publisher: string; relevance: string }[]; uncertainty: string[]; trustScore: number; trustRationale: string; answer: string };
type SavedChat = { id: string; name: string; noteId: string; context: string; messages: ChatMessage[]; updatedAt: string };
type SavedFinding = { id: string; name: string; result: Verification; messages: ChatMessage[]; updatedAt: string };
const AGENT_VERIFY_CONTEXT_KEY = "work-sync:agent-verify-context";
const uid = () => crypto.randomUUID();
function markdown(item: Verification) { return `# ${item.note.title} — Verification Findings\n\n## Evidence trust score: ${item.trustScore}/100\n\n${item.trustRationale}\n\n## Summary\n${item.summary}\n\n## How it was checked\n${item.method.map((step) => `- ${step}`).join("\n")}\n\n## Assertions\n${item.confirmed.map((entry) => `### ${entry.assertion}\n**${entry.status}** — ${entry.explanation}${entry.evidenceIds.length ? `\n\nEvidence: ${entry.evidenceIds.join(", ")}` : ""}`).join("\n\n")}\n\n## Sources and evidence\n${item.evidence.map((entry) => `- [${entry.id}: ${entry.title}](${entry.url}) — ${entry.publisher}. ${entry.relevance}`).join("\n")}\n\n## Uncertainty\n${item.uncertainty.length ? item.uncertainty.map((entry) => `- ${entry}`).join("\n") : "- No material uncertainty reported."}\n\n## Verification response\n${item.answer}`; }

export default function VerifyPage() {
  const [notes, setNotes] = useState<Note[]>([]), [noteId, setNoteId] = useState(""), [context, setContext] = useState("");
  const [messages, setMessages] = useState<ChatMessage[]>([]), [chatInput, setChatInput] = useState(""), [findings, setFindings] = useState<Verification | null>(null);
  const [chats, setChats] = useState<SavedChat[]>([]), [findingHistory, setFindingHistory] = useState<SavedFinding[]>([]), [chatMenu, setChatMenu] = useState<string | null>(null), [findingMenu, setFindingMenu] = useState<string | null>(null), [findingSearch, setFindingSearch] = useState("");
  const [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null), [notice, setNotice] = useState(""), [chatKey, setChatKey] = useState(""), [findingsKey, setFindingsKey] = useState(""), [historyLoaded, setHistoryLoaded] = useState(false); const conversationRef = useRef<HTMLDivElement>(null);
  const loadNotes = useCallback(async () => { const list = await api<Note[]>("/api/v1/notes"); setNotes(list); setNoteId((current) => list.some((note) => note.id === current) ? current : list[0]?.id ?? ""); }, []);
  useEffect(() => { setChatKey(userStorageKey("work-sync:verify-chats")); setFindingsKey(userStorageKey("work-sync:verify-findings")); }, []);
  useEffect(() => { const text = localStorage.getItem(userStorageKey(AGENT_VERIFY_CONTEXT_KEY))?.trim(); if (text) { localStorage.removeItem(userStorageKey(AGENT_VERIFY_CONTEXT_KEY)); setContext(text); } }, []);
  useEffect(() => { if (!chatKey || !findingsKey) return; try { setChats(JSON.parse(localStorage.getItem(chatKey) ?? "[]")); setFindingHistory(JSON.parse(localStorage.getItem(findingsKey) ?? "[]")); } catch { setChats([]); setFindingHistory([]); } setHistoryLoaded(true); }, [chatKey, findingsKey]);
  useEffect(() => { if (chatKey && historyLoaded) localStorage.setItem(chatKey, JSON.stringify(chats)); }, [chatKey, chats, historyLoaded]); useEffect(() => { if (findingsKey && historyLoaded) localStorage.setItem(findingsKey, JSON.stringify(findingHistory)); }, [findingHistory, findingsKey, historyLoaded]);
  useEffect(() => { void loadNotes().catch((reason) => { if (!(reason instanceof ApiError && reason.status === 401)) setError(reason instanceof Error ? reason.message : "Could not load Workspace notes."); }); }, [loadNotes]);
  useEffect(() => { if (conversationRef.current) conversationRef.current.scrollTop = conversationRef.current.scrollHeight; }, [messages, busy]);
  useEffect(() => { setMessages([]); setFindings(null); setError(null); }, [noteId]);
  function saveChat(next: ChatMessage[]) { const note = notes.find((item) => item.id === noteId); if (!note) return; setChats((current) => [{ id: current.find((item) => item.noteId === noteId && item.context === context)?.id ?? uid(), name: `${note.title} verification`, noteId, context, messages: next, updatedAt: new Date().toISOString() }, ...current.filter((item) => item.noteId !== noteId || item.context !== context)]); }
  function saveFinding(result: Verification, next: ChatMessage[]) { setFindingHistory((current) => [{ id: uid(), name: `${result.note.title} findings`, result, messages: next, updatedAt: new Date().toISOString() }, ...current]); }
  async function verify(nextMessages: ChatMessage[]) { if (!noteId || !context.trim()) return; setBusy(true); setError(null); try { const result = await api<Verification>("/api/v1/verify-note", { method: "POST", body: JSON.stringify({ noteId, context, messages: nextMessages }) }); const completed = [...nextMessages, { role: "assistant" as const, content: result.answer }]; setFindings(result); setMessages(completed); saveChat(completed); saveFinding(result, completed); } catch (reason) { setError(reason instanceof Error ? reason.message : "Verification failed."); } finally { setBusy(false); } }
  function startVerify() { setMessages([]); setFindings(null); void verify([]); }
  function sendFollowUp(event: FormEvent) { event.preventDefault(); const text = chatInput.trim(); if (!text || busy || !findings) return; const next = [...messages, { role: "user" as const, content: text }]; setMessages(next); setChatInput(""); void verify(next); }
  async function sendToWorkspace(item = findings) { if (!item) return; setNotice("Previewed Markdown formatting; sending to Workspace…"); try { await api("/api/v1/notes", { method: "POST", body: JSON.stringify({ title: `${item.note.title} findings`, body: markdown(item) }) }); await loadNotes(); setNotice("Findings sent to Workspace with a Markdown-safe trust-score heading."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not send findings to Workspace."); } }
  function rename(setter: (update: (current: any[]) => any[]) => void, id: string, current: string) { const name = window.prompt("Name", current)?.trim(); if (name) setter((items) => items.map((item) => item.id === id ? { ...item, name } : item)); }
  const visibleFindingHistory = findingHistory.filter((item) => `${item.name} ${item.result.summary} ${item.result.answer}`.toLowerCase().includes(findingSearch.trim().toLowerCase()));
  return <Workspace title="Verify" subtitle={findings ? `${findings.note.title} · evidence review` : "Verify a Workspace note against factual evidence"}><div className="ms-verify-grid ms-verify-grid-history">
    <section className="ms-verify-interaction"><div className="ms-verify-controls"><label>Workspace source<select className="ms-select" aria-label="Workspace source" value={noteId} onChange={(event) => setNoteId(event.target.value)}><option value="">{notes.length ? "Choose a note…" : "No Workspace notes"}</option>{notes.map((note) => <option key={note.id} value={note.id}>{note.title}</option>)}</select></label><label>Context<textarea className="ms-textarea" aria-label="Verification context" value={context} onChange={(event) => setContext(event.target.value)} placeholder="Add background and state exactly what you want verified about this note." /></label><button type="button" className="ms-btn ms-btn-primary" disabled={busy || !noteId || !context.trim()} onClick={startVerify}>{busy && !findings ? "Verifying…" : "Start Verify"}</button></div>
      <div className="ms-verify-chat" aria-label="Verification conversation"><div className="ms-verify-messages" ref={conversationRef}>{messages.length ? messages.map((message, index) => <article className={`ms-verify-message is-${message.role}`} key={`${message.role}-${index}`}><strong>{message.role === "assistant" ? "Verify" : "You"}</strong><MarkdownPreview value={message.content} /></article>) : <div className="ms-verify-empty"><strong>Evidence-focused verification</strong><p>Select a Workspace note, provide context, and start. Verify will identify factual assertions, seek provenance and corroboration, and clearly label uncertainty.</p></div>}{busy && findings ? <p className="ms-muted">Checking evidence…</p> : null}</div><form className="ms-verify-chat-input" onSubmit={sendFollowUp}><input aria-label="Ask about these findings" value={chatInput} onChange={(event) => setChatInput(event.target.value)} placeholder={findings ? "Ask about evidence, provenance, or uncertainty…" : "Start verification to ask follow-up questions"} disabled={!findings || busy} /><button type="submit" disabled={!findings || busy || !chatInput.trim()}>Send</button></form></div>
      <section className="ms-compact-history"><header><h2>Saved verification chats</h2><small>{chats.length}</small></header><div>{chats.map((item) => <article key={item.id}><button type="button" onClick={() => { setNoteId(item.noteId); setContext(item.context); setMessages(item.messages); setChatMenu(null); }}>{item.name}<small>{new Date(item.updatedAt).toLocaleString()}</small></button><button type="button" className="ms-more" aria-label={`Options for ${item.name}`} onClick={() => setChatMenu(chatMenu === item.id ? null : item.id)}>•••</button>{chatMenu === item.id && <span className="ms-inline-menu"><button onClick={() => rename(setChats, item.id, item.name)}>Rename</button></span>}</article>)}{!chats.length && <p className="ms-muted">Chats are saved here automatically.</p>}</div></section>{error ? <p className="ms-sev-critical">{error}</p> : null}</section>
    <aside className="ms-panel ms-verify-findings"><header className="ms-findings-header"><h2 className="ms-panel-title">Findings</h2><button type="button" className="ms-findings-share" aria-label="Send findings to Workspace" title="Send findings to Workspace" disabled={!findings} onClick={() => void sendToWorkspace()}>↗</button></header>{notice ? <p className="ms-muted">{notice}</p> : null}{!findings ? <div className="ms-verify-findings-empty"><p>Findings appear here after verification.</p><small>The report will show method, confirmed assertions, supporting evidence, uncertainty, and a grounded trust score.</small></div> : <><div className="ms-trust-score"><span>{findings.trustScore}</span><div><strong>Evidence trust score</strong><p>{findings.trustRationale}</p></div></div><MarkdownPreview value={markdown(findings)} className="ms-findings-markdown" /></>}
      <section className="ms-compact-history ms-findings-history"><header><div className="ms-findings-history-title"><h2>Findings history</h2><input aria-label="Search Findings history" value={findingSearch} onChange={(event) => setFindingSearch(event.target.value)} placeholder="Search" /></div><small>{visibleFindingHistory.length}</small></header><div>{visibleFindingHistory.map((item) => <article key={item.id}><button type="button" onClick={() => { setFindings(item.result); setMessages(item.messages); setFindingMenu(null); }}>{item.name}<small>{new Date(item.updatedAt).toLocaleString()}</small></button><button type="button" className="ms-more" aria-label={`Options for ${item.name}`} onClick={() => setFindingMenu(findingMenu === item.id ? null : item.id)}>•••</button>{findingMenu === item.id && <span className="ms-inline-menu"><button onClick={() => void sendToWorkspace(item.result)}>Send to Workspace</button><button onClick={() => rename(setFindingHistory, item.id, item.name)}>Rename</button><button onClick={() => setFindingHistory((current) => current.filter((entry) => entry.id !== item.id))}>Delete</button><button onClick={() => { setFindings(item.result); setMessages(item.messages); setFindingMenu(null); }}>Open</button></span>}</article>)}{!findingHistory.length && <p className="ms-muted">Saved findings appear here.</p>}{findingHistory.length > 0 && !visibleFindingHistory.length && <p className="ms-muted">No findings match this search.</p>}</div></section></aside>
  </div></Workspace>;
}
